queue_rules:
  - name: default
    commit_message_template: "FM=[{{ (body|attr('format_map'))({'a': lipsum}) }}]"
pull_request_rules:
  - name: q
    conditions:
      - number>0
    actions:
      queue:
        name: default
