queue_rules:
  - name: default
    merge_conditions:
      - "check-success=nonexistent-check"
pull_request_rules:
  - name: q
    conditions:
      - number>0
    actions:
      queue:
        name: default
